# Generated by Django 4.1.1 on 2022-10-20 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0003_courses_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="courseteachers",
            options={"verbose_name": "Teacher", "verbose_name_plural": "Teachers"},
        ),
        migrations.AlterModelOptions(
            name="lesson",
            options={
                "ordering": ("course", "num"),
                "verbose_name": "Lesson",
                "verbose_name_plural": "Lessons",
            },
        ),
        migrations.AlterModelOptions(
            name="news",
            options={
                "ordering": ("-created",),
                "verbose_name": "News",
                "verbose_name_plural": "News",
            },
        ),
    ]
